version: '3.4'

services:
  identitydb:
    container_name: identitydb
    environment:
      - SA_PASSWORD=Pass#word1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/var/opt/mssql/data
  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings__IdentityProviderConnection=Server=identitydb;Initial Catalog=IdentityDB;Persist Security Info=False;User ID=sa;Password=Pass#word1;MultipleActiveResultSets=False;TrustServerCertificate=true;Connection Timeout=130;"
      - TokenLifetimeMinutes=2000
      - PermanentTokenLifetimeDays=500
      - CookieLifeTime=2
    ports:
      - 5000:443
    depends_on: 
      - identitydb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./IdentityServer/wwwroot:/app/wwwroot