version: '3.4'

services:
  identitydb2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: identitydb2

  pushtokendb:
    image: mongo

  bookcatalogdb:
      container_name: bookcatalogdb
      image: postgres:14
  
  basketdb:
    container_name: basketdb
    image: redis:alpine

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.12
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: ./IdentityServer/Dockerfile

  purchasetokenapi:
    image: ${DOCKER_REGISTRY-}purchasetokenapi
    build:
      context: .
      dockerfile: ./Purchasetoken.API/Dockerfile

  bookcatalogapi:
    image: ${DOCKER_REGISTRY-}bookcatalogapi
    build:
      context: .
      dockerfile: ./BookCatalog.API/Dockerfile
  
  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: ./Basket.API/Dockerfile

volumes:
  pushtokendb_mongo_data:
  bookcatalogdb_data:
