version: '3.4'

services:
  identitydb2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: identitydb2
  pushtokendb:
    image: mongo
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: ./IdentityServer/Dockerfile
  purchasetokenapi:
    image: ${DOCKER_REGISTRY-}purchasetokenapi
    build:
      context: .
      dockerfile: ./Purchasetoken.API/Dockerfile

volumes:
  pushtokendb_mongo_data:
