version: "3.4"

services:
  identitydb2:
    container_name: identitydb2
    environment:
      - SA_PASSWORD=Pass#word1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./sql:/var/opt/mssql/data

  pushtokendb:
    container_name: pushtokendb
    restart: always
    ports:
      - "27030:27017"
    volumes:
      - pushtokendb_mongo_data:/data/db

  bookcatalogdb:
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Pass#word1
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - bookcatalogdb_data:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      - bookcatalogdb
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=Pass#word1
    ports:
      - 8080:80

  identityserver:
    container_name: identityserver
    hostname: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ConnectionStrings__IdentityProviderConnection=Server=identitydb2;Initial Catalog=IdentityServerDb;Persist Security Info=False;User ID=sa;Password=Pass#word1;MultipleActiveResultSets=False;TrustServerCertificate=true;Connection Timeout=130;"
      - TokenLifetimeMinutes=2000
      - PermanentTokenLifetimeDays=500
      - CookieLifeTime=2
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass#word1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5044:443
    depends_on:
      - identitydb2
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./IdentityServer/wwwroot:/app/wwwroot

  purchasetokenapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - idp_url=https://identityserver
      - ConnectionString=mongodb://pushtokendb
      - DatabaseName=TokenAccountDb
      - CollectionName=TokenAccount
      - ScopeName=GatewayScope API
      - client_secret=Pass#word1
      - client_id=9b0444ee-91ac-4f6c-a5a3-e82aef9126b4
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass#word1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5045:443
    volumes:
      - ~/.aspnet/https:/https:ro

  bookcatalogapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - idp_url=https://identityserver
      - ConnectionStrings__PostgreSQLConnection=Host=bookcatalogdb;Username=admin;Password=Pass#word1;Enlist=false;Database=BookCatalog
      - ScopeName=GatewayScope API
      - client_secret=Pass#word1
      - client_id=2d4a5ab0-65d5-4c2e-8aaf-202d5f2f2df5
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass#word1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 5046:443
    volumes:
      - ~/.aspnet/https:/https:ro
