version: '3.4'

services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: identitydb
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
